### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by GuilhermeStipp** [INWTlab/ireports#14]
Hello good afternoon.

If I want to "justify" the written text, how do I change the script or the .TEX file?

Thank you.

**Comment by SarahWagner** [comment]
Hello @GuilhermeStipp95, 

in the `defs.tex` file in section `misc` try to replace the command `\raggedright` with `\centering`.

**Comment by GuilhermeStipp** [comment]
Thank you very much @SarahWagner.

I need to make two modifications. The first was to add the package "ragged2e" and in the "misc" section, use "\justifying".
