### ISSUE TITLE
Error message when knitting 

### ISSUE THREAD

**Issue by MandyKlatt** [INWTlab/ireports#17]
Hi!

When I try to knit the business report I get the following message:

error: LaTeX failed to compile businessreporttemplate.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips.
Additional: Warning messages:
1: In .alignStringToVector(value) : Nonstandard alignments in align string
2: In system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) :
  '"xelatex"' not found
Execution stopped

Can anyone give me any advice on what to do?

Thanks a lot.

Best
Mandy

**Comment by SarahWagner** [comment]
Hello @MandyKlatt,
I'll take a look where that error comes from. 
Can you try to knit the document again after installing the tinytex package? It provides a latex distribution for R users. Here are more information on the package: https://yihui.org/tinytex/

```r
install.packages('tinytex')
tinytex::install_tinytex()
# to uninstall TinyTeX, run tinytex::uninstall_tinytex() 
```
