### ISSUE TITLE
fully justified text

### ISSUE THREAD

**Issue by GregorKachel** [INWTlab/ireports#18]
Dear INWTlab,
the template is great. I just started using it. Right now I'm trying to format the text such that it is fully justified, i.e. spreads equally across the lines. I tried various things in the YAML and intext and will continue to search.
Do you maybe know right away how to do this?

**Comment by SarahWagner** [comment]
Hello @GregorKachel, thank you! Please take a look at this issue: https://github.com/INWTlab/ireports/issues/14 Does this solve your problem?

**Comment by GregorKachel** [comment]
Yes! Thanks! Sorry for not seeing the earlier request right away.
