### ISSUE TITLE
Knitting to Word instead of PDF

### ISSUE THREAD

**Issue by tanga94** [INWTlab/ireports#20]
Hi! I'm wondering, is there any way to knit this template as a Word Doc instead of a PDF?

**Comment by SarahWagner** [comment]
Hi @tanga94, I'm sorry, but only pdf is supported.

**Comment by tanga94** [comment]
Thanks @SarahWagner . Sorry if this is unrelated to my previous question, but is there any way to get your template into a two column, landscape format?
