### ISSUE TITLE
How to get figures to appear and hold in position when using a multicolumn format?

### ISSUE THREAD

**Issue by tanga94** [INWTlab/ireports#21]
Hi @SarahWagner. I'm having a bit of trouble getting figures to appear in your template as soon as I try to use a multicolumn format. I've added the following packages to your ```defs.tex``` file in order get my document to be landscape as well as two columns

```
\usepackage{multicol}
\usepackage[landscape]{geometry}
```

When I start to add text to my Rmd, that works perfectly. But as soon as I add a simple figure in a code chunk like this

````````````
```{r fig1, fig.align='center', fig.cap="First Plot \\label{Figure1}", fig.height=2.4, fig.width=2}

library(ggplot2)

mtcars$cyl <- as.factor(mtcars$cyl)

ggplot(mtcars, aes(x=hp, y=mpg, color=cyl, shape=cyl)) +
  geom_point(size=3)

```
``````````````

The figure just doesn't appear in my document. I had a look and I think it's because figures can't float within a multicolumn environment (see [https://tex.stackexchange.com/a/458533/199349](url)). Is there any way to replicate the *figure trick that this LaTeX user did in an Rmarkdown file? Or any other ways to get figures to appear in the exact position they're in within my Rmd file?

Thanks so much!

**Comment by SarahWagner** [comment]
Hi @tanga94, with the example you provided, the ggplot figure does appear in my document. To make it appear in the exact position, I usually define and print ggplots in two different chunks, like so: 

![image](https://user-images.githubusercontent.com/8091552/109166425-faa99580-777c-11eb-92b5-7f793fa553a6.png)

There is also a fig.show argument that you could try out, for that please take a look at the knitr documentation: https://yihui.org/knitr/options/#plots

Let me know if that resolves your issue.
