### ISSUE TITLE
Include Preview Rmd file

### ISSUE THREAD

**Issue by DavisBrian** [INWTlab/ireports#5]
Would it be possible to include the Rmd file used to generate the document in the README Preview as a reproducible example?  I'm having problems getting this package to work.

**Comment by SarahWagner** [comment]
@DavisBrian Would you please describe what exactly does not work or which kind of error occurs, respectively?

**Comment by wahani** [comment]
If you find the time, your RMD file would be very helpful to diagnose any problems.

**Comment by DavisBrian** [comment]
@SarahWagner The problem ended up being that the contents of the inst folder are not installed.  So the template wasn't showing up in RStudio.  I had tried copying the YAML header from the README (which isn't the one used by the template it doesn't seem) over the default rmarkdown pdf document, which obviously won't work.  Downloading the contents of the inst folder and copying them into package directory solved the problem.
