### ISSUE TITLE
ZIP install

### ISSUE THREAD

**Issue by afontoura** [INWTlab/ireports#8]
This report template is exactly what I'm looking for,  but thanks to my company firewall, I can't install packages from github at work. Would you provide a ZIP version for download and install via RStudio?

**Comment by SarahWagner** [comment]
@afontoura Sure, I'll get back to you with the zipped package asap.

**Comment by SarahWagner** [comment]
@afontoura There you go. Let me know if this worked for you. 

[IReports_0.11.0.tar.gz](https://github.com/INWTlab/ireports/files/2909583/IReports_0.11.0.tar.gz)

**Comment by afontoura** [comment]
Thanks a lot, Sarah. I'll test it and let you know the results.
